### ISSUE TITLE
Lack of detailed instruction to use

### ISSUE THREAD

**Issue by warmjaijai** [JackPu/vue2.x-core-image-upload#2]
Hi, I am rather new to this and failed to get it to work. It would be much appreciated if more detailed instruction is provided so more people (newbie like me) can use your package more easily.

I got an error saying  

> Property or method "imageuploaded" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 

which is pointed out from the events session of yours, do I have to add that event somewhere in order to get it work?

**Comment by saleh-old** [comment]
I have the same problem! The package looks really cool but the installation is not suitable for newbies like me.

**Comment by geekgirlcoding** [comment]
@warmjaijai  - the reason for that error is that imageuploaded is used when the vue template is called, but the tutorial shows it being called imageUploaded in the methods section - the change in case makes a difference

**Comment by JackPu** [comment]
@warmjaijai  You can view new doc [here](https://github.com/Vanthink-UED/vue-core-image-upload). The project will be removed soon.
